#!/bin/bash
set -e
LOGFILE2=/var/log/gunicorn/majka-celerycam-stderr.log
LOGFILE1=/var/log/gunicorn/majka-celerycam-stdout.log

cd /home/programmer/dev/projects/majka/majka
source /home/programmer/dev/virtualenvs/majka/bin/activate
exec /home/programmer/dev/virtualenvs/majka/bin/python manage.py celerycam 2>>$LOGFILE2 1>>$LOGFILE1
